#' Get user's progress
#'
#' @param subject_id Get progress information for a given subject.
#' @param format Result will be a list of json data when set to \code{list}
#' (default), \code{response()} object when set to \code{default}, and a
#' \code{data.table} when set to \code{table}.
#' @param token Bangumi access token which is generated by \code{bgm_auth()}.
#'
#' @return A list of json data in list, \code{response()} object, or a
#' \code{data.table} contains the progress.
#' @export
#'
#' @examples
#' \dontrun{
#' bgm_progress()
#' }
bgm_progress <- function(subject_id = NULL,
                              format = c("list", "table", "default"),
                              token = bgm_get_token()) {
  # config
  base <- "https://api.bgm.tv/user/%s/progress"
  limited_args <- list(
    "format" = match.arg(format, c("list", "table", "default"))
  )

  # get resource
  res <- httr::GET(
    # no matter the user name or id, only return authenticated user's progress
    url = sprintf(base, "unknown"),
    query = c(
      limited_args,
      "subject_id" = subject_id
    ),
    config = token
  )
  content <- httr::content(res)

  # return
  return(switch(
    limited_args$format,
    list = content,
    default = res,
    table = json_to_df(content)
  ))
}
